kind: ConfigMap
apiVersion: v1
metadata:
  name: sender
  labels:
    app: sender
data:
  SOURCE: 'sender'
  GROUP: 'senders'
  HOSTS: 'kubemq-cluster-grpc-headless.kubemq:50000'
  CHANNEL: ''
  TYPE: 'queue'
  CLIENT_ID: ''
  CHANNEL-START-RANGE: '0'
  SENDERS: '500'
  SEND_BATCH: '15'
  SEND_INTERVAL: '1000'
  LOAD_INTERVAL: '100'
  KILL_AFTER: '0'
  PAYLOAD_SIZE: '5000'
  PAYLOAD_File: ''
  COLLECT_EVERY: '5'
  VERBOSE: 'false'
  DURATION: ""
  TOTAL_MESSAGES: "75000"
  CONCURRENCY: "1"
  COLLECTOR-URL: 'http://collector.apps:8085'
