kind: Deployment
apiVersion: apps/v1
metadata:
  name: sender
spec:
  replicas: 10
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
        - name: sender
          image: 'docker.io/kubemq/showcase-sender:v0.2.0'
          envFrom:
            - configMapRef:
                name: sender
          resources: {}
          imagePullPolicy: Always
