kind: Deployment
apiVersion: apps/v1
metadata:
  name: receiver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
    spec:
      containers:
        - name: receiver
          image: 'docker.io/kubemq/showcase-receiver:v0.2.0'
          envFrom:
            - configMapRef:
                name: receiver
          resources: {}
          imagePullPolicy: Always
