version: '3'

tasks:
  init:
    cmds:
      - kubectl apply -f ./namespace.yaml
      - helm repo add kubemq-charts  https://kubemq-io.github.io/charts
      - helm repo update
      - helm install kubemq-operator kubemq-charts/operator -n kubemq
  deploy:
    cmds:
      - helm install kubemq-cluster kubemq-charts/kubemq --values ./values.yaml -n kubemq

  upgrade:
    cmds:
      - helm upgrade kubemq-cluster kubemq-charts/kubemq --values ./values.yaml -n kubemq

  delete:
    cmds:
      - helm delete kubemq-cluster -n kubemq

  old_deploy:
    cmds:
      - kubectl apply -f ./old/statefulset.yaml -n kubemq
      - kubectl apply -f ./old/config.yaml -n kubemq
      - kubectl apply -f ./old/service.yaml -n kubemq
      - kubectl apply -f ./old/secret.yaml -n kubemq
  old_delete:
    cmds:
      - kubectl delete -f ./old/statefulset.yaml -n kubemq
      - kubectl delete -f ./old/config.yaml -n kubemq
      - kubectl delete -f ./old/service.yaml -n kubemq
      - kubectl delete -f ./old/secret.yaml -n kubemq
