POST http://localhost:8085/report
Content-Type: application/json

{
  "source": "sender-1",
  "group": "senders",
  "instance": "sender-1-1",
  "clients": 100,
  "messages": 1000000,
  "volume": 50030,
  "errors": 20,
  "pending": 100000
}
###
POST http://localhost:8085/report
Content-Type: application/json

{
  "source": "sender-1",
  "group": "senders",
  "instance": "sender-1-2",
  "clients": 100,
  "messages": 100,
  "volume": 50000
}
###
POST http://localhost:8085/report
Content-Type: application/json

{
  "source": "sender-2",
  "group": "senders",
  "instance": "sender-1-1",
  "clients": 100,
  "messages": 100,
  "volume": 50000
}
###
POST http://localhost:8085/report
Content-Type: application/json

{
  "source": "receiver-1",
  "group": "receivers",
  "instance": "receiver-1-1",
  "clients": 100,
  "messages": 100,
  "volume": 50000,
  "errors": 100
}
###
POST http://localhost:8085/report
Content-Type: application/json

{
  "source": "receiver-2",
  "group": "receivers",
  "instance": "receiver-1-1",
  "clients": 100,
  "messages": 1000,
  "volume": 50000,
  "errors": 100
}
###
POST http://localhost:8085/report
Content-Type: application/json

{
  "source": "receiver-3",
  "group": "receivers",
  "instance": "receiver-1-1",
  "clients": 10000,
  "messages": 1000,
  "volume": 50000,
  "errors": 100
}
