kind: ConfigMap
apiVersion: v1
metadata:
  name: collector
  labels:
    app: collector
data:
  KUBEMQ_HOSTS: "kubemq-cluster-0.kubemq-cluster.default:8080,kubemq-cluster-1.kubemq-cluster.default:8080,kubemq-cluster-2.kubemq-cluster.default:8080"
  API_SERVER_URL: "http://localhost:8085"
  API_SERVER_PORT: '8085'
  CONSOLE: 'false'
