kind: Deployment
apiVersion: apps/v1
metadata:
  name: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
        - name: sender
          image: 'docker.io/kubemq/showcase-collector:v0.3.0'
          envFrom:
            - configMapRef:
                name: collector
          ports:
            - name: api-port
              containerPort: 8085
              protocol: TCP
          resources: {}
          imagePullPolicy: Always
